---
notifications:
  email:
    - craig@cwatson.org
sudo: false
language: ruby
dist: trusty
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  include:
  - rvm: 2.4.0
    env: PUPPET_GEM_VERSION="~> 5.1.0"
  - rvm: 2.4.0
    env: PUPPET_GEM_VERSION="~> 5.0.0"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
